/** @class Schema_Sabitler */
module.exports = {
    /** @class DOSYA_YOLLARI */
    DOSYA_YOLLARI: [
        '../schemas/providers/login/ActiveDirectory.js',
        '../schemas/providers/login/providerFacebook.js',
        '../schemas/providers/login/providerGooglePlus.js',
        '../schemas/providers/login/providerTwitter.js',
        '../schemas/providers/login/index.js',
        '../schemas/dogrulama/index.js',
        // ./ORTAK/
        '../schemas/ortak/sehir.js',
        '../schemas/ortak/bolge.js',
        '../schemas/ortak/ulke.js',
        '../schemas/ortak/anahtarKelime.js',
        '../schemas/ortak/dosyaEki.js',
        '../schemas/ortak/dovizKuru.js',
        '../schemas/ortak/grafikDonut.js',
        '../schemas/ortak/grafikDonut_urun_teklif_onay.js',
        '../schemas/ortak/onayDurumu.js',
        '../schemas/ortak/kalem.js',
        '../schemas/ortak/kalem_es.js',
        '../schemas/ortak/kalem_db.js',
        '../schemas/ortak/kurum.js',
        '../schemas/ortak/kurum_es.js',
        '../schemas/ortak/kurum_db.js',
        '../schemas/ortak/ihale.js',
        '../schemas/ortak/ihale_es.js',
        '../schemas/ortak/ihale_db.js',
        '../schemas/ortak/lazyLoadingResponse.js',
        '../schemas/ortak/sayfalama.js',
        '../schemas/ortak/siralama.js',
        '../schemas/ortak/teklif.js',
        '../schemas/ortak/teklif_es.js',
        '../schemas/ortak/teklif_db.js',
        '../schemas/ortak/url_query.js',
        '../schemas/ortak/urun.js',
        '../schemas/ortak/urun_es.js',
        '../schemas/ortak/urun_db.js',
        '../schemas/ortak/uyari_kriter.js',
        '../schemas/ortak/uyari_db.js',
        '../schemas/ortak/uyari.js',
        '../schemas/ortak/paylas_ids.js',
        '../schemas/ortak/haber.js',
        '../schemas/tahta/ajanda.js',
        // ./KULLANICI/
        '../schemas/kullanici/kullaniciGiris.js',
        '../schemas/kullanici/kullanici_giris_yapan_session.js',
        '../schemas/kullanici/kullanici_giris_yapan_browser.js',
        '../schemas/kullanici/kullaniciKayit.js',

        '../schemas/kullanici/kullanici_es.js',
        '../schemas/kullanici/kullanici_db.js',
        '../schemas/kullanici/uye_davet.js',
        '../schemas/kullanici/uye.js',
        // ./ROL_YETKILENDIRME/
        '../schemas/rol_yetkilendirme/crud.js',
        '../schemas/rol_yetkilendirme/yetki.js',
        '../schemas/rol_yetkilendirme/rol.js',
        '../schemas/rol_yetkilendirme/tahtaRolu.js',
        // ./PROVIDERS/
        '../schemas/providers/ihale/saglikbank.js',
        '../schemas/providers/ihale/ekap.js',
        '../schemas/providers/ihale/ihaleDunyasi.js',
        '../schemas/providers/ihale/index.js',
        // ./TAHTA/
        '../schemas/tahta/index.js',
        //kullanıcı
        '../schemas/kullanici/kullanici.js'
    ],

    /**
     * @class SCHEMA_ID
     */
    SCHEMA_ID: {
        DB: {
            KURUM: "/node/schema/ortak/kurum_db",
            KALEM: "/node/schema/ortak/kalem_db",
            URUN: "/node/schema/ortak/urun_db",
            IHALE: "/node/schema/ortak/ihale_db",
            KULLANICI: "/node/schema/kullanici/kullanici_db",
            TEKLIF: "/node/schema/ortak/teklif_db",
            UYARI: "/node/schema/ortak/uyari_db"
        },
        ES: {
            KURUM: "/node/schema/ortak/kurum_es",
            KALEM: "/node/schema/ortak/kalem_es",
            URUN: "/node/schema/ortak/urun_es",
            IHALE: "/node/schema/ortak/ihale_es",
            TEKLIF: "/node/schema/ortak/teklif_es",
            KULLANICI: "/node/schema/kullanici/kullanici_es"
        },
        SEHIR: "/node/schema/ortak/sehir",
        BOLGE: "/node/schema/ortak/bolge",
        ULKE: "/node/schema/ortak/ulke",
        INDEX_DOGRULAMA: "/node/schema/dogrulama/index",
        ANAHTAR_KELIME: "/node/schema/ortak/anahtarKelime",
        DOSYA_EKI: "/node/schema/ortak/dosyaEki",
        DOVIZ_KURU: "/node/schema/ortak/dovizKuru",
        GRAFIK_DONUT: "/node/schema/ortak/grafikDonut",
        GRAFIK_DONUT_URUN_TEKLIF_ONAY: "/node/schema/ortak/grafikDonut_urunTeklifOnay",
        IHALE: "/node/schema/ortak/ihale",
        KALEM: "/node/schema/ortak/kalem",
        KULLANICI: "/node/schema/kullanici/kullanici",
        UYE: "/node/schema/kullanici/uye",
        KURUM: "/node/schema/ortak/kurum",
        LAZY_LOADING_RESPONSE: "/node/schema/ortak/lazyLoadingResponse",
        ONAY_DURUM: "/node/schema/ortak/onayDurumu",
        SAYFALAMA: "/node/schema/ortak/sayfalama",
        SIRALAMA: "/node/schema/ortak/siralama",
        TEKLIF: "/node/schema/ortak/teklif",
        URL_QUERY: "/node/schema/ortak/url_query",
        URUN: "/node/schema/ortak/urun",
        HABER: "/node/schema/ortak/haber",
        PAYLAS_IDS: "/node/schema/ortak/paylas_ids",
        UYARI: "/node/schema/ortak/uyari",
        UYARI_KRITER: "/node/schema/ortak/uyari_kriter",
        EKAP: "/node/schema/providers/ihale/ekap",
        IHALE_DUNYASI: "/node/schema/providers/ihale/ihaleDunyasi",
        INDEX_IHALE: "/node/schema/providers/ihale/index",
        SAGLIKBANK: "/node/schema/providers/ihale/saglikbank",
        INDEX_LOGIN: "/node/schema/providers/login/index",
        LOGIN_AD: "/node/schema/providers/login/ActiveDirectory",
        LOGIN_FB: "/node/schema/providers/login/providerFacebook",
        LOGIN_GP: "/node/schema/providers/login/providerGooglePlus",
        LOGIN_TW: "/node/schema/providers/login/providerTwitter",
        INDEX_TAHTA: "/node/schema/tahta/index",
        //rol_yetkilendirme
        CRUD: "/node/schema/rol_yetkilendirme/CRUD",
        TAHTA_ROLU: "/node/schema/rol_yetkilendirme/tahtaRolu",
        ROL: "/node/schema/rol_yetkilendirme/rol",
        UYE_DAVET: "/node/schema/kullanici/uyeDavet",
        KULLANICI_GIRIS: "/node/schema/kullanici/kullaniciGiris",
        KULLANICI_KAYIT: "/node/schema/kullanici/kullaniciKayit",
        KULLANICI_SESSION: "/node/schema/kullanici/kullaniciSession",
        KULLANICI_BROWSER: "/node/schema/kullanici/kullaniciBrowser"
    }
};